# don't build tags, it's redundant
skip_tags: true

clone_depth: 5

environment:
  matrix:
    - nodejs_version: 10
    - nodejs_version: 9
    - nodejs_version: 8
    - nodejs_version: 6
    
install:
  - choco install googlechrome --ignore-checksums 
  - ps: Update-NodeJsInstallation (Get-NodeJsLatestBuild $env:nodejs_version)
  - node --version
  - npm --version
  - npm install

test_script:
  - npm test

build: off

cache:
  - node_modules
